import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import Image from 'next/image'
import page1 from '../public/web1.png'
import page2 from '../public/web2.png'
import page3 from '../public/web3.png'
import page4 from '../public/web4.png'
import { useState } from 'react'



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <>
      <div className={darkMode ? 'dark' : ""}>
        <Head>
          <title>Guilherme Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800'>
          <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-roboto dark:text-white'>Guilherme Dine</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
                </li>
                <li>
                  <a className='bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href="#">
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            <div className='text-center p-10 py-10'>
              <h2 className='text-5xl py-2 text-cyan-600 font-medium md:text-6xl'>Guilherme Dine</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Web Developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>I am looking for an opportunity to enter the world of programming.</p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <a target={'_blank'} href='https://www.linkedin.com/in/guilherme-dine-83a17a242/'>
                <AiFillLinkedin className='cursor-pointer dark:text-white' />
              </a>
              <a target={'_blank'} href='https://github.com/Guilhermedine'>
                <AiFillGithub className='cursor-pointer dark:text-white' />
              </a>
            </div>
          </section>
          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Espaços pro juan me ajudar a preencher com o que eu sei fazer</p>
            </div>
            <div className='lg:flex gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={page1} width={1300} height={1300} className='mx-auto' />
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Web Pages</h3>
                <p className='py-2 dark:text-gray-300'>
                  Creating elegant pages suited for your needs.
                </p>
                <h4 className='py-4 text-teal-600'>Tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-300'>React</p>
                <p className='text-gray-800 py-1 dark:text-gray-300'>Typescript</p>
                <p className='text-gray-800 py-1 dark:text-gray-300'>Styled-components</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={page2} width={1300} height={1300} className='mx-auto' />
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Web Pages</h3>
                <p className='py-2 dark:text-gray-300'>
                  Creating elegant pages suited for your needs.
                </p>
                <h4 className='py-4 text-teal-600'>Tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-300'>React</p>
                <p className='text-gray-800 py-1 dark:text-gray-300'>Typescript</p>
                <p className='text-gray-800 py-1 dark:text-gray-300'>Styled-components</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Espaços pro juan me ajudar a preencher com o que eu sei fazer</p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1'>
                <Image src={page3} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src={page4} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              </div>
            </div>
          </section>
          <section>
            <div className='text-center py-10'>
              <h3 className='text-3xl py-1 dark:text-white'>Contact</h3>
              <p className='text-md text-gray-800 dark:text-gray-300'>Phone Number: +55 11 948762672</p>
              <p className='text-md text-gray-800 dark:text-gray-300'>E-mail: guilherme.dine@gmail.com</p>
            </div>
          </section>
        </main>
      </div>
    </>
  )
}
